### ISSUE TITLE
Milestone 2 feedback

### ISSUE THREAD

**Issue by gurmehak** [UBC-MDS/heart-failure-analysis#62]
hi guys! pls reflect on these and incorporate by :

- [x] move jupyter notebook into src folder + render html/pdf 
- [ ] cleanup/remove temp files - place them in .gitignore
- [ ] combine requirements.txt with environment file (need confirmation on this)
- [ ] description before each step justifying your work
