### ISSUE TITLE
Milestone 4 work

### ISSUE THREAD

**Issue by gurmehak** [UBC-MDS/heart-failure-analysis#92]
- [ ] create the makefile
- [ ]  run and test docker
- [ ] create 4 functions for the scripts
- [ ] work on feedback (8)
